name: aci

services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
    environment:
      - SERVER_OPENAI_API_KEY=${SERVER_OPENAI_API_KEY}
      - CLI_OPENAI_API_KEY=${CLI_OPENAI_API_KEY}
      - GERALT_SECRET=${GERALT_SECRET}
